### ISSUE TITLE
Resources$NotFoundException when attempting to start Sensors Activity

### ISSUE THREAD

**Issue by jakehockey10** [jakehockey10/Sunshine#1]
There is a Sensors item in the menu drop down.  The intent was to start the Sensors Activity when this menu item is clicked.  Instead, a Resources$NotFoundException is thrown.  The following is the stack trace:

```
02-09 19:58:55.002  11919-11919/com.example.jake.sunshine E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.jake.sunshine, PID: 11919
    android.content.res.Resources$NotFoundException: Resource ID #0x0
            at android.content.res.Resources.getValue(Resources.java:2333)
            at android.content.res.Resources.loadXmlResourceParser(Resources.java:3881)
            at android.content.res.Resources.getLayout(Resources.java:2149)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
            at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
            at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
            at android.widget.AbsListView.obtainView(AbsListView.java:2842)
            at android.widget.ListView.makeAndAddView(ListView.java:1884)
            at android.widget.ListView.fillDown(ListView.java:713)
            at android.widget.ListView.fillFromTop(ListView.java:779)
            at android.widget.ListView.layoutChildren(ListView.java:1693)
            at android.widget.AbsListView.onLayout(AbsListView.java:2632)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16668)
            at android.view.ViewGroup.layout(ViewGroup.java:5302)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2313)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2026)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1185)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6591)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
            at android.view.Choreographer.doCallbacks(Choreographer.java:590)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5837)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
```

**Comment by jakehockey10** [comment]
Issue has been resolved.  I followed the general direction of [this](https://github.com/codepath/android_guides/wiki/Using-an-ArrayAdapter-with-ListView) to setup my own custom ArrayAdapter<Sensor>.
